server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.151.130:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: mysql
    show-sql: true
  redis:
    host: 47.94.151.130
  rabbitmq:
    host: 47.94.151.130
